from django.urls import path

from crm.views import (
    change_user_password,
    create_customer,
    create_product,
    create_product_category,
    create_service,
    create_user,
    customers,
    delete_customer,
    delete_product,
    delete_product_category,
    delete_service,
    delete_user,
    edit_customer,
    edit_product,
    edit_product_category,
    edit_profile,
    edit_service,
    edit_user,
    home,
    product_categories,
    products,
    services,
    system_settings,
    users,
)

urlpatterns = [
    path("", home, name="home"),
    path("customers/", customers, name="customers"),
    path("customers/create/", create_customer, name="create_customer"),
    path("customers/<int:customer_id>/edit/", edit_customer, name="edit_customer"),
    path("customers/<int:customer_id>/delete/", delete_customer, name="delete_customer"),
    path("product-categories/", product_categories, name="product_categories"),
    path("product-categories/create/", create_product_category, name="create_product_category"),
    path("product-categories/<int:category_id>/edit/", edit_product_category, name="edit_product_category"),
    path("product-categories/<int:category_id>/delete/", delete_product_category, name="delete_product_category"),
    path("products/", products, name="products"),
    path("products/create/", create_product, name="create_product"),
    path("products/<int:product_id>/edit/", edit_product, name="edit_product"),
    path("products/<int:product_id>/delete/", delete_product, name="delete_product"),
    path("services/", services, name="services"),
    path("services/create/", create_service, name="create_service"),
    path("services/<int:service_id>/edit/", edit_service, name="edit_service"),
    path("services/<int:service_id>/delete/", delete_service, name="delete_service"),
    path("profile/", edit_profile, name="edit_profile"),
    path("system-settings/", system_settings, name="system_settings"),
    path("users/", users, name="users"),
    path("users/create/", create_user, name="create_user"),
    path("users/<int:user_id>/edit/", edit_user, name="edit_user"),
    path("users/<int:user_id>/change-password/", change_user_password, name="change_user_password"),
    path("users/<int:user_id>/delete/", delete_user, name="delete_user"),
]
