# Generated by Django 6.0.1 on 2026-03-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_productcategory_product_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My CRM', max_length=150)),
                ('default_currency', models.CharField(choices=[('ZAR', 'South African Rand (ZAR)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)')], default='ZAR', max_length=3)),
            ],
            options={
                'verbose_name': 'system settings',
                'verbose_name_plural': 'system settings',
            },
        ),
    ]
