# Generated by Django 6.0.1 on 2026-03-29 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_access_rows_for_existing_admins(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    UserAccess = apps.get_model("crm", "UserAccess")

    for user in User.objects.filter(is_staff=True) | User.objects.filter(is_superuser=True):
        UserAccess.objects.update_or_create(
            user=user,
            defaults={"can_manage_configuration": True},
        )


def remove_access_rows(apps, schema_editor):
    UserAccess = apps.get_model("crm", "UserAccess")
    UserAccess.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_systemsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_configuration', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user access',
                'verbose_name_plural': 'user access',
            },
        ),
        migrations.RunPython(create_access_rows_for_existing_admins, remove_access_rows),
    ]
