# Generated by Codex on 2026-03-29

from django.conf import settings
from django.db import migrations


CRM_USER_GROUP = "CRM User"
CRM_ADMIN_GROUP = "CRM Admin"
SYSTEM_ADMIN_GROUP = "System Admin"
ROLE_GROUP_NAMES = (
    CRM_USER_GROUP,
    CRM_ADMIN_GROUP,
    SYSTEM_ADMIN_GROUP,
)


def migrate_access_levels_to_groups(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    Group = apps.get_model("auth", "Group")
    UserAccess = apps.get_model("crm", "UserAccess")

    groups = {
        name: Group.objects.get_or_create(name=name)[0]
        for name in ROLE_GROUP_NAMES
    }
    admin_user_ids = set(
        UserAccess.objects.filter(can_manage_configuration=True).values_list("user_id", flat=True)
    )

    for user in User.objects.all():
        if user.is_superuser or user.is_staff:
            desired_group = groups[SYSTEM_ADMIN_GROUP]
        elif user.id in admin_user_ids:
            desired_group = groups[CRM_ADMIN_GROUP]
        else:
            desired_group = groups[CRM_USER_GROUP]
        user.groups.add(desired_group)


def rollback_access_level_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=ROLE_GROUP_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_useraccess"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(migrate_access_levels_to_groups, rollback_access_level_groups),
    ]
